export const GET_PROJECTS = "GET_PROJECTS"
export const REGISTER_PROJECTS = "REGISTER_PROJECTS"
export const ALTER_PROJECTS = "ALTER_PROJECTS"
export const REMOVE_PROJECTS = "REMOVE_PROJECTS"

export const GET_TASKS = "GET_TASKS"
export const DEFINE_TASKS = "DEFINE_TASKS"
export const REGISTER_TASKS  = "REGISTER_TASKS"